// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbgetuixbstujvlrmels.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZ2V0dWl4YnN0dWp2bHJtZWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTIyODUsImV4cCI6MjA3MDk4ODI4NX0.ij6oU6Wk88Zix4mHlbQf6UHKb3rLtuRpymyOtP46BN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});